### PR TITLE
Peer dependencies should be dev dependencies

### PR DESCRIPTION
**Pull request by hwaterke**

### CODE REVIEW

**Comment by int64ago** [comment]
Why?

**Comment by hwaterke** [comment]
The library requires react to work (that's why it is specified as a peer dependency).
The problem if you also specify it as a dependency is that react will be installed as well when using your library.
If I want to use the library in my app, it will install its own react and I'll end up with two different react versions

**Comment by int64ago** [comment]
> it will install its own react and I'll end up with two different react versions

Where will be a warning if the versions are different between local and peerDep.

Also, devDep doesn't solve the multi-version problem.

**Comment by int64ago** [comment]
Close for timeout, feel free to reopen if necessary.

**Comment by int64ago** [comment]
Close for timeout, feel free to reopen if necessary.

**Pull request closed without merging**
